### ISSUE TITLE
Configure ScalaAFA

### ISSUE THREAD

**Issue by ZiyangJiao** [ChaseLab-PKU/ScalaAFA#1]
Thanks for making the codebase of this work publicly available!

I have configured ScalaAFA on our server according to the README. However, I have a few questions regarding the configuration settings:

**1. The default ScalaAFA is configured as a 4+1 RAID5 system, using 5 devices (NVMe0 - NVMe4). Can we add more devices to build a 5+1 system?**

**2. Is it possible to change the parity level to build a RAID6 system (e.g., 4+2 AFA)?**

I appreciate your insights!

**Comment by FirnYi** [comment]
Yes, ScalaAFA can be run with more SSD and configured as RAID 6.

To add more SSDs:

1. Please modify the FEMU configuration `run-scalaafa.sh` in `ScalaAFA/femu/build-femu`: add a new line `-device femu,devsz_mb=40960,femu_mode=1`. 
2. Afterward, when you execute `sudo HUGEMEM=10240 scripts/setup.sh` in Step 8, you will see a new PCIe traddr. Just add it to the configuration file, i.e., `ScalaAFA/spdk/test/config_afa.json`.



To use RAID6 mode:

1. Modify `num_parity_base_bdevs` in  `ScalaAFA/spdk/test/config_afa.json` as 2.

**Comment by ZiyangJiao** [comment]
Thank you very much for the instructions!
